deployments:
  environmentMapping:
    development:
      - "dev*"
    testing:
      - "qa*"
    staging:
      - "sb*"
      - "sandbox*"
      - "yts1"
    production:
      - "prod*"
      - "yt1"
      - "PROD-*"
