name: CI

on:
push:
branches: [PRB-1]
pull_request:
branches: [PRB-1]

jobs: 
deploy:
name: Deploy
runs-on: ubuntu-latest
environment: production

steps:
- uses: actions/checkout@v2
- name: Run a one-line script
run: echo Hello, world!
- name: Run a multi-line script
run: |
echo Add other actions to build,
echo test, and deploy your project.
